--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: kubdocker201
    environment: development
    version: "1.0"
  name: kubdocker201-v1.0
  namespace: nl-amis-development
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: kubdocker201
      environment: development
      version: "1.0"
  template: 
    metadata: 
      labels: 
        app: kubdocker201
        environment: development
        version: "1.0"
    spec: 
      containers: 
        - 
          env: 
            - 
              name: spring.profiles.active
              value: development
          image: "kubdocker201:v1.0"
          name: kubdocker201-v1-0-container
          ports: 
            - 
              containerPort: 9090
