--- 
apiVersion: v1
kind: PersistentVolume
metadata: 
  labels: 
    type: local
  name: mysql-persistent-volume
  namespace: nl-amis-testing
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath: 
    path: /mnt/data
  storageClassName: manual
