--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pv-claim
  namespace: nl-amis-testing
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: manual