--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: kubdocker201
    environment: testing
    version: "1.0"
  name: kubdocker201-v1-0-service
  namespace: nl-kub-testing
spec: 
  ports: 
    - 
      nodePort: 30110
      port: 9191
      protocol: TCP
      targetPort: 9091
  selector: 
    app: kubdocker201
    environment: testing
    version: "1.0"
  type: NodePort
