--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: mysql
    environment: testing
    version: "1.0"
  name: mysql-service
  namespace: nl-amis-testing
spec: 
  clusterIP: None
  ports: 
    - 
      port: 3306
  selector: 
    app: mysql
